### ISSUE TITLE
[Bug]: when i try to run webui

### ISSUE THREAD

**Issue by cardry1** [Sygil-Dev/sygil-webui#1661]
### What happened?

Environment name is set as ldm as per environment.yaml
anaconda3/miniconda3 detected in C:\Users\User\anaconda3
Stashing local changes and pulling latest update...
fatal: detected dubious ownership in repository at 'E:/stable diffusion/sygil-webui'
'E:/stable diffusion/sygil-webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/stable diffusion/sygil-webui'
fatal: detected dubious ownership in repository at 'E:/stable diffusion/sygil-webui'
'E:/stable diffusion/sygil-webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/stable diffusion/sygil-webui'
fatal: detected dubious ownership in repository at 'E:/stable diffusion/sygil-webui'
'E:/stable diffusion/sygil-webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/stable diffusion/sygil-webui'
fatal: detected dubious ownership in repository at 'E:/stable diffusion/sygil-webui'
'E:/stable diffusion/sygil-webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/stable diffusion/sygil-webui'
Current  environment.yaml hash:
Previous environment.yaml hash: ECHO is off.
environment.yaml changed. updating dependencies

CondaValueError: prefix already exists: C:\Users\User\anaconda3\envs\ldm

Collecting package metadata (repodata.json): done
Solving environment: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\Users\\User\\anaconda3\\envs\\ldm\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'E:\\stable diffusion\\sygil-webui\\condaenv.0pfalvmn.requirements.txt']
Pip subprocess output:
Obtaining file:///E:/stable%20diffusion/sygil-webui (from -r E:\stable diffusion\sygil-webui\requirements.txt (line 1))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers#egg=taming-transformers (from -r E:\stable diffusion\sygil-webui\requirements.txt (line 6))

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\vcs\git.py", line 367, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\commands\install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 322, in __init__
    super().__init__(
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 332, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\operations\prepare.py", line 629, in prepare_editable_requirement
    req.update_editable()
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\req\req_install.py", line 634, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url, verbosity=0)
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 526, in obtain
    existing_url = self.get_remote_url(dest)
  File "C:\Users\User\anaconda3\envs\ldm\lib\site-packages\pip\_internal\vcs\git.py", line 369, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

failed

CondaEnvException: Pip failed

Your model file does not exist! Once the WebUI launches please visit the Model Manager page and download the models by using the Download button for each model.

  Welcome to Streamlit!

  If you’d like to receive helpful onboarding emails, news, offers, promotions,
  and the occasional swag, please enter your email address below. Otherwise,
  leave this field blank.

  Email:

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cstueckrath** [comment]
is E:\ an NTFS formatted drive?

**Comment by cardry1** [comment]
yes, i think so

**Comment by cardry1** [comment]
im pretty new to all this

**Comment by cstueckrath** [comment]
do you mean like an USB hard drive?
Rightclick drive in Explorer, Properties, File System reads NTFS?

**Comment by cardry1** [comment]
![image](https://user-images.githubusercontent.com/118081556/201546534-a1b19002-46b4-4b3e-a92c-c6d086233d9c.png)

**Comment by cardry1** [comment]
no it does not

**Comment by cstueckrath** [comment]
you will have to change that to NTFS by reformatting (losing all the files if not copied away) or use another drive then.
While Sygil will work on an exFAT drive, all the git stuff and the cmds will behave weirdly.
We will definitely not support this setup.

**Comment by cardry1** [comment]
i used another method and got another error 
venv "C:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing torch and torchvision
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\launch.py", line 255, in <module>
    prepare_enviroment()
  File "C:\ai\stable-diffusion-webui\launch.py", line 173, in prepare_enviroment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\ai\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\ai\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 2
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch==1.12.1+cu113

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 134, in __call__
    resp = _http_get_download(self._session, link)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 117, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 125, in unpackb
    ret = unpacker._unpack()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 544, in _unpack
    typ, n, obj = self._read_header()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 486, in _read_header
    obj = self._read(n)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 403, in _read
    ret = self._buffer[i : i + n]
MemoryError

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: C:\ai\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip


Press any key to continue . . .

**Comment by cardry1** [comment]
updating gives me another error

**Comment by cardry1** [comment]
so

**Comment by cstueckrath** [comment]
`Error code: 2` is usually linked to a device error (maybe your drive has errors or it might be out of space?)

**Comment by cardry1** [comment]
how can i tell if the driver has errors?
and if its out of space
