### ISSUE TITLE
[Bug]: FileNotFoundError: Could not find module "...gfortran-win_amd64.dll"

### ISSUE THREAD

**Issue by Maxxxel** [Sygil-Dev/sygil-webui#1714]
### What happened?

I just started the webui.cmd and let it update. Now it wont start and i get an error. Legacy also fails with the same error.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "D:\AI\sygil-webui\scripts\webui_streamlit.py", line 22, in <module>
    from sd_utils import st, hc, load_configs, load_css, set_logger_verbosity,\
  File "scripts\sd_utils\__init__.py", line 43, in <module>
    from scipy import integrate
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\user\miniconda3\envs\ldm\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\user\miniconda3\envs\ldm\lib\site-packages\scipy\.libs\libbanded5x.7PE4S675VJ62Q2FNVPMD7F5FIF53EQIT.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maxxxel** [comment]
Deleted the repo and miniconda and reinstalled all. Works again.
