### ISSUE TITLE
[Bug]: Submit button in Settings missing & indexerror

### ISSUE THREAD

**Issue by DOUBLEXX666** [Sygil-Dev/sygil-webui#1727]
### What happened?

Indexerror: 

File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
File "D:\AI\sygil-webui\scripts\webui_streamlit.py", line 203, in <module>
    layout()
File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\loguru\_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
File "D:\AI\sygil-webui\scripts\webui_streamlit.py", line 192, in layout
    layout()
File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\loguru\_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
File "scripts\Settings.py", line 56, in layout
    help=f"Select which GPU to use. Default: {device_list[0]}").split(":")[0])

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cstueckrath** [comment]
do you have multiple GPUs (linke integrated and dedicated)?
What GPU are you running?

**Comment by DOUBLEXX666** [comment]
I currently have a RX 5700 xt

**Comment by BADNaMe-RK** [comment]
I have the same issue, but I have Windows with GTX1650 and integrated intel. And everything worked well until today. Now I have the same problem with index error and "AssertionError: Torch not compiled with CUDA enabled" if I try to launch the generation, but I think it has the same reason. I've checked requirements from requirements.txt 
[log.txt](https://github.com/Sygil-Dev/sygil-webui/files/10403188/log.txt)

IndexError: list index out of range
2023-01-12 18:36:17.412 Uncaught app exception
Traceback (most recent call last):
  File "F:\Miniconda3\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "F:\Stable diffusion\sygil-webui\scripts\webui_streamlit.py", line 203, in <module>
    layout()
  File "F:\Miniconda3\envs\ldm\lib\site-packages\loguru\_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "F:\Stable diffusion\sygil-webui\scripts\webui_streamlit.py", line 192, in layout
    layout()
  File "F:\Miniconda3\envs\ldm\lib\site-packages\loguru\_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "scripts\Settings.py", line 56, in layout
    help=f"Select which GPU to use. Default: {device_list[0]}").split(":")[0])
IndexError: list index out of range

**Comment by kiam001** [comment]
thx @BADNaMe-RK  also fixes the problem for me with windows 11 and rtx 2060

**Comment by yiqiangjun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
