### ISSUE TITLE
[Bug]: TypeError: CacheDataAPI.__call__() got an unexpected keyword argument 'suppress_st_warning'

### ISSUE THREAD

**Issue by mikecastrodemaria** [Sygil-Dev/sygil-webui#1781]
### What happened?

Hi

On a mbp M1, when I lanche the ./webui.sh and follow the proccess I get :

`...../miniconda3/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(...../miniconda3/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: <F0D48035-EF9E-3141-9F63-566920E60D7C> /miniconda3/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <97D13A69-B703-3555-89F4-B5036A18B675> ...../miniconda3/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
2023-05-03 17:12:37.797 Uncaught app exception
Traceback (most recent call last):
  File "...../miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File ".....SD-sygil-webui/scripts/webui_streamlit.py", line 22, in <module>
    from sd_utils import st, hc, load_configs, load_css, set_logger_verbosity,\
  File ".....SD-sygil-webui/scripts/sd_utils/__init__.py", line 1760, in <module>
    @st.experimental_memo(persist="disk", show_spinner=False, suppress_st_warning=True)
TypeError: CacheDataAPI.__call__() got an unexpected keyword argument 'suppress_st_warning'
2023-05-03 17:13:00.882 Uncaught app exception
Traceback (most recent call last):
  File "...../miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File ".....SD-sygil-webui/scripts/webui_streamlit.py", line 22, in <module>
    from sd_utils import st, hc, load_configs, load_css, set_logger_verbosity,\
  File ".....SD-sygil-webui/scripts/sd_utils/__init__.py", line 1760, in <module>
    @st.experimental_memo(persist="disk", show_spinner=False, suppress_st_warning=True)
TypeError: CacheDataAPI.__call__() got an unexpected keyword argument 'suppress_st_warning'`

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jenkshow** [comment]
I also encountered this problem. Have you solved it?

**Comment by ZeroCool940711** [comment]
Hey guys, can you check if the hotfix I just made fixed the issue for you?
I removed the `suppress_st_warning` argument from the decorator that was causing the issue so it should be fixed.

**Comment by jenkshow** [comment]
gI suspect there is an issue with streamlit.  After using "pip install --upgrade streamlit," I received the following message: "st.experimental_memo is deprecated.  Please use the new command st.cache_data instead, which has the same behavior.  More information in our docs."

StreamlitAPIException: set_page_config() can only be called once per app page, and must be called as the first Streamlit command in your script.

For more information, please refer to the documentation.

Traceback:
File "/Users/jenk/Documents/sygil-webui-master/stable-diffusion-webui/scripts/webui_streamlit.py", line 203, in <module>
layout()
File "/Users/jenk/anaconda3/lib/python3.10/site-packages/loguru/_logger.py", line 1251, in catch_wrapper
return function(*args, **kwargs)
File "/Users/jenk/Documents/sygil-webui-master/stable-diffusion-webui/scripts/webui_streamlit.py", line 76, in layout
st.set_page_config(page_title="Stable Diffusion Playground", layout="wide", initial_sidebar_state="collapsed")

**Comment by ZeroCool940711** [comment]
Do not upgrade streamlit, they love breaking stuff on every single update, that's why I locked the streamlit version we use to an older version to make sure things would work even after streamlit update stuff, the error about `st.set_page_config()` is weird, it should be only set once in the whole code, so, no idea why its throwing that, will look into it.
