### ISSUE TITLE
win11 install error  No module named 'altair.vegalite.v4' 

### ISSUE THREAD

**Issue by Kedaranatha** [Sygil-Dev/sygil-webui#1785]
Dear, any ideas about this install problem on windows 11. 
I'm following step by step https://sygil-dev.github.io/sygil-webui/docs/Installation/windows-installation/

Thank you!

"Your model file does not exist! Once the WebUI launches please visit the Model Manager page and download the models by using the Download button for each model.
2023-05-25 22:31:10.981 INFO    matplotlib.font_manager: generated new fontManager
Traceback (most recent call last):
  File "C:\Users\kedar\anaconda3\envs\ldm\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\kedar\anaconda3\envs\ldm\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\kedar\anaconda3\envs\ldm\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\kedar\anaconda3\envs\ldm\lib\site-packages\streamlit\__init__.py", line 57, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\kedar\anaconda3\envs\ldm\lib\site-packages\streamlit\delta_generator.py", line 46, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "C:\Users\kedar\anaconda3\envs\ldm\lib\site-packages\streamlit\elements\arrow_altair.py", line 35, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
"

**Comment by jagg2** [comment]
Ran into the same issue on linux install, was able to fix it by fallowing this fix https://discuss.huggingface.co/t/streamlit-spaces-with-modulenotfounderror-no-module-named-altair-vegalite-v4-error/39683
