### ISSUE TITLE
[Bug]: Stable Diff - Jsonmerge not found

### ISSUE THREAD

**Issue by NiceWonBruva** [Sygil-Dev/sygil-webui#1824]
### What happened?

DOWNLOADING STABLE DIFFUSIOIN

Same issue... no jsonmerge 

  File "C:\STABLE DIF\sd.webui\webui\repositories\k-diffusion\k_diffusion\config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
Press any key to continue . . .

rtx4070
i7-13700k
48gbram
m.2 4tb

Surely I have the processing power... just need more in my head to work this all out >.< Someone helppp

May re-download items an alternative way. Maybe not doing the Nvidia download but following the AUTOMATIC1111 might work...?
Any advice would be loved<3
<img width="869" alt="Screenshot 2023-10-24 182722" src="https://github.com/Sygil-Dev/sygil-webui/assets/139145366/65195025-2f72-438e-8cd8-4f0201ce0c94">

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
venv "C:\STABLE DIF\sd.webui\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\STABLE DIF\sd.webui\webui\launch.py", line 48, in <module>
    main()
  File "C:\STABLE DIF\sd.webui\webui\launch.py", line 44, in main
    start()
  File "C:\STABLE DIF\sd.webui\webui\modules\launch_utils.py", line 432, in start
    import webui
  File "C:\STABLE DIF\sd.webui\webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\STABLE DIF\sd.webui\webui\modules\initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "C:\STABLE DIF\sd.webui\webui\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "C:\STABLE DIF\sd.webui\webui\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, shared
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "C:\STABLE DIF\sd.webui\webui\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "C:\STABLE DIF\sd.webui\webui\repositories\k-diffusion\k_diffusion\config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
Press any key to continue . . .venv "C:\STABLE DIF\sd.webui\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\STABLE DIF\sd.webui\webui\launch.py", line 48, in <module>
    main()
  File "C:\STABLE DIF\sd.webui\webui\launch.py", line 44, in main
    start()
  File "C:\STABLE DIF\sd.webui\webui\modules\launch_utils.py", line 432, in start
    import webui
  File "C:\STABLE DIF\sd.webui\webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\STABLE DIF\sd.webui\webui\modules\initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "C:\STABLE DIF\sd.webui\webui\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "C:\STABLE DIF\sd.webui\webui\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, shared
  File "C:\STABLE DIF\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "C:\STABLE DIF\sd.webui\webui\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "C:\STABLE DIF\sd.webui\webui\repositories\k-diffusion\k_diffusion\config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
Press any key to continue . . .
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nitinmukesh** [comment]
I faced the exact same problem yesterday with Automatic1111 and I deleted and reinstalled.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15796

I know both are different projects but no harm in trying.
